name: TaberCore
author: Sam Taber
version: 1.0
main: com.samtaber.main.Main
commands:
   download:
      aliases: dl
      description: Download TaberAddon(s) from deployment server.
   loadaddon:
      aliases: loadadd
      description: Load TaberAddon(s) into system.